### ISSUE TITLE
porting to Rust

### ISSUE THREAD

**Issue by iamgabrielsoft** [eshikafe/bess-rs#1]
I would like to port some section of the core folder to Rust

**Comment by eshikafe** [comment]
Thanks @iamgabrielsoft for willing to contribute. 
Please select any .cc/.h file in the `/core` folder that you are comfortable with and start porting.

Kindly provide feedback here on the C++ files you are working on.

**Comment by eshikafe** [comment]
This is better tracked under `Projects`
